"""add profile columns to students

Revision ID: 4e76e7e83c4d
Revises: d7bb14424621
Create Date: 2026-04-19 03:28:08.446771

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e76e7e83c4d'
down_revision: Union[str, Sequence[str], None] = 'd7bb14424621'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('first_name', sa.String(length=255), nullable=True))
    op.add_column('students', sa.Column('last_name', sa.String(length=255), nullable=True))
    op.add_column('students', sa.Column('matriculation_number', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'matriculation_number')
    op.drop_column('students', 'last_name')
    op.drop_column('students', 'first_name')
    # ### end Alembic commands ###
