"""add course_files and student_file_progress

Revision ID: 70671ff7afb1
Revises: 4e76e7e83c4d
Create Date: 2026-04-19 08:02:52.520526

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "70671ff7afb1"
down_revision: str | Sequence[str] | None = "4e76e7e83c4d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "course_files",
        sa.Column("dataset_name", sa.String(length=100), nullable=False),
        sa.Column("s3_key", sa.String(length=500), nullable=False),
        sa.Column("filename", sa.String(length=500), nullable=False),
        sa.Column("display_name", sa.String(length=500), nullable=False),
        sa.Column("category", sa.String(length=20), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("core_concepts", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("s3_key"),
    )
    op.create_index(
        op.f("ix_course_files_dataset_name"), "course_files", ["dataset_name"], unique=False
    )
    op.create_table(
        "student_file_progress",
        sa.Column("student_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("course_file_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("completed", sa.Boolean(), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["course_file_id"], ["course_files.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["students.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "uq_student_file_progress",
        "student_file_progress",
        ["student_id", "course_file_id"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("uq_student_file_progress", table_name="student_file_progress")
    op.drop_table("student_file_progress")
    op.drop_index(op.f("ix_course_files_dataset_name"), table_name="course_files")
    op.drop_table("course_files")
    # ### end Alembic commands ###
