"""add agent_activities table

Revision ID: d7bb14424621
Revises: cf4fd9ea4e0f
Create Date: 2026-04-19 02:17:58.492894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd7bb14424621'
down_revision: Union[str, Sequence[str], None] = 'cf4fd9ea4e0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_activities',
    sa.Column('student_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('agent', sa.String(length=50), nullable=False),
    sa.Column('icon', sa.String(length=10), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_agent_activities_student_created', 'agent_activities', ['student_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_agent_activities_student_id'), 'agent_activities', ['student_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agent_activities_student_id'), table_name='agent_activities')
    op.drop_index('ix_agent_activities_student_created', table_name='agent_activities')
    op.drop_table('agent_activities')
    # ### end Alembic commands ###
